---
# Example using grafana
version: '3'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - VIRTUAL_HOST=othersubdomain.yourdomain.tld
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=othersubdomain.yourdomain.tld
      - LETSENCRYPT_EMAIL=mail@yourdomain.tld

networks:
  default:
    name: nginx-proxy-acme_default
    external: true
